services:
  - type: web
    name: performance-cycle-fbt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
